// Wszystkie oferty – dane używane na liście i stronie szczegółów
var OFERTY = [
    {
        id: 1,
        nazwa: 'Grecja – Santorini',
        badge: 'Last Minute',
        badgeKolor: 'red',
        gwiazdki: '★★★★★',
        dni: 7,
        wyzywienie: 'All Inclusive',
        lotnisko: 'Warszawa',
        cena: 2499,
        lastminute: true,
        destination: 'grecja',
        zdjecie: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&h=450&fit=crop',
        opis: 'Odkryj magię Santorini – białe domy z niebieskimi kopułami, zapierające dech w piersiach zachody słońca i krystalicznie czyste Morze Egejskie. Idealne miejsce dla par szukających romantycznych chwil oraz osób pragnących odpocząć od codzienności.',
        wlaczone: ['Przelot w obie strony', 'All Inclusive', 'Transfer z lotniska', 'Ubezpieczenie', 'Opieka pilota']
    },
    {
        id: 2,
        nazwa: 'Egipt – Hurghada',
        badge: 'Bestseller',
        badgeKolor: 'green',
        gwiazdki: '★★★★☆',
        dni: 10,
        wyzywienie: 'All Inclusive',
        lotnisko: 'Katowice',
        cena: 1899,
        lastminute: false,
        destination: 'egipt',
        zdjecie: 'https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=800&h=450&fit=crop',
        opis: 'Hurghada to raj dla miłośników nurkowania i plażowania. Morze Czerwone zachwyca bogactwem podwodnego życia, a hotele oferują światowy poziom obsługi. Słońce świeci tu przez cały rok.',
        wlaczone: ['Przelot w obie strony', 'All Inclusive', 'Transfer z lotniska', 'Ubezpieczenie', 'Opieka pilota']
    },
    {
        id: 3,
        nazwa: 'Turcja – Antalya',
        badge: 'Promocja',
        badgeKolor: '',
        gwiazdki: '★★★★★',
        dni: 7,
        wyzywienie: 'All Inclusive',
        lotnisko: 'Warszawa',
        cena: 1699,
        lastminute: false,
        destination: 'turcja',
        zdjecie: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=800&h=450&fit=crop',
        opis: 'Antalya to perła tureckiej Riwiery. Luksusowe hotele z rozległymi basenami, piaszczyste plaże i bogata historia czekają na Ciebie. Doskonały wybór dla rodzin z dziećmi.',
        wlaczone: ['Przelot w obie strony', 'All Inclusive', 'Transfer z lotniska', 'Ubezpieczenie', 'Animacje dla dzieci']
    },
    {
        id: 4,
        nazwa: 'Hiszpania – Teneryfa',
        badge: 'Nowość',
        badgeKolor: 'green',
        gwiazdki: '★★★★☆',
        dni: 14,
        wyzywienie: 'Śniadania',
        lotnisko: 'Wrocław',
        cena: 3199,
        lastminute: false,
        destination: 'hiszpania',
        zdjecie: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800&h=450&fit=crop',
        opis: 'Teneryfa to największa z Wysp Kanaryjskich, gdzie wulkaniczne krajobrazy spotykają się z tropikalną roślinnością. Odwiedź Teide – najwyższy szczyt Hiszpanii i jeden z największych wulkanów świata.',
        wlaczone: ['Przelot w obie strony', 'Śniadania', 'Transfer z lotniska', 'Ubezpieczenie']
    },
    {
        id: 5,
        nazwa: 'Włochy – Sycylia',
        badge: 'Polecane',
        badgeKolor: '',
        gwiazdki: '★★★★☆',
        dni: 7,
        wyzywienie: 'Half Board',
        lotnisko: 'Gdańsk',
        cena: 2299,
        lastminute: false,
        destination: 'wlochy',
        zdjecie: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800&h=450&fit=crop',
        opis: 'Sycylia to wyspa pełna kontrastów – starożytne ruiny, barokowe miasteczka, smaczna kuchnia i ciepłe morze. Odwiedź Palermo, Syrakuzy i Etnę w jednym niezapomnianym wyjeździe.',
        wlaczone: ['Przelot w obie strony', 'Half Board', 'Transfer z lotniska', 'Ubezpieczenie', 'Zwiedzanie z przewodnikiem']
    },
    {
        id: 6,
        nazwa: 'Tajlandia – Phuket',
        badge: 'Egzotyka',
        badgeKolor: 'red',
        gwiazdki: '★★★★★',
        dni: 14,
        wyzywienie: 'Śniadania',
        lotnisko: 'Warszawa',
        cena: 4999,
        lastminute: false,
        destination: 'tajlandia',
        zdjecie: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&h=450&fit=crop',
        opis: 'Phuket to klejnot Tajlandii – szmaragdowe wody, białe plaże, świątynie i nocne targi pełne egzotycznych smaków. Idealne połączenie relaksu i przygody w tropikalnym klimacie.',
        wlaczone: ['Przelot w obie strony', 'Śniadania', 'Transfer z lotniska', 'Ubezpieczenie', 'Wycieczka na wyspy']
    },
    {
        id: 7,
        nazwa: 'Portugalia – Algarve',
        badge: 'Polecane',
        badgeKolor: '',
        gwiazdki: '★★★★☆',
        dni: 10,
        wyzywienie: 'Śniadania',
        lotnisko: 'Kraków',
        cena: 2799,
        lastminute: false,
        destination: 'portugalia',
        zdjecie: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&h=450&fit=crop',
        opis: 'Algarve to południowy kraniec Portugalii słynący z malowniczych klifów, złotych plaż i pysznych owoców morza. Odkryj urok Faro, Lagos i Sagres w jednej wyjątkowej podróży.',
        wlaczone: ['Przelot w obie strony', 'Śniadania', 'Transfer z lotniska', 'Ubezpieczenie']
    },
    {
        id: 8,
        nazwa: 'Chorwacja – Dubrownik',
        badge: 'Last Minute',
        badgeKolor: 'red',
        gwiazdki: '★★★★☆',
        dni: 7,
        wyzywienie: 'Half Board',
        lotnisko: 'Warszawa',
        cena: 1999,
        lastminute: true,
        destination: 'chorwacja',
        zdjecie: 'https://images.unsplash.com/photo-1626808642875-0aa545482dfb?w=800&h=450&fit=crop',
        opis: 'Dubrownik – Perła Adriatyku. Stare Miasto wpisane na listę UNESCO, turkusowe morze i urokliwe wysepki. Spacer murami miejskimi o zachodzie słońca to niezapomniane przeżycie.',
        wlaczone: ['Przelot w obie strony', 'Half Board', 'Transfer z lotniska', 'Ubezpieczenie']
    },
    {
        id: 9,
        nazwa: 'Maroko – Marrakesz',
        badge: 'Egzotyka',
        badgeKolor: 'red',
        gwiazdki: '★★★★☆',
        dni: 8,
        wyzywienie: 'Śniadania',
        lotnisko: 'Katowice',
        cena: 2199,
        lastminute: true,
        destination: 'maroko',
        zdjecie: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800&h=450&fit=crop',
        opis: 'Marrakesz urzeka tętniącymi życiem soukami, pałacami i ogrodami. Plac Dżamaa el-Fna to serce miasta, gdzie kuglarze, muzycy i sprzedawcy tworzą niezapomniany spektakl.',
        wlaczone: ['Przelot w obie strony', 'Śniadania', 'Transfer z lotniska', 'Ubezpieczenie', 'Wycieczka po Medinie']
    },
    {
        id: 10,
        nazwa: 'Bali – Indonezja',
        badge: 'Egzotyka',
        badgeKolor: 'red',
        gwiazdki: '★★★★★',
        dni: 14,
        wyzywienie: 'Śniadania',
        lotnisko: 'Warszawa',
        cena: 5499,
        lastminute: false,
        destination: 'indonezja',
        zdjecie: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&h=450&fit=crop',
        opis: 'Bali to wyspa bogów – tarasowe pola ryżowe, świątynie wśród dżungli i tętniące życiem plaże. Ubud, Seminyak i Uluwatu to trzy oblicza tej magicznej wyspy.',
        wlaczone: ['Przelot w obie strony', 'Śniadania', 'Transfer z lotniska', 'Ubezpieczenie', 'Wycieczka do świątyń']
    },
    {
        id: 11,
        nazwa: 'Malediwy',
        badge: 'Luksus',
        badgeKolor: 'red',
        gwiazdki: '★★★★★',
        dni: 10,
        wyzywienie: 'All Inclusive',
        lotnisko: 'Warszawa',
        cena: 8999,
        lastminute: false,
        destination: 'malediwy',
        zdjecie: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&h=450&fit=crop',
        opis: 'Malediwy to synonim raju na ziemi – bungalowy na wodzie, krystaliczne laguny i niesamowite rafy koralowe. Idealne miejsce dla par szukających absolutnego luksusu i prywatności.',
        wlaczone: ['Przelot w obie strony', 'All Inclusive', 'Transfer łodzią', 'Ubezpieczenie', 'Nurkowanie i snorkeling']
    },
    {
        id: 12,
        nazwa: 'Dubaj – ZEA',
        badge: 'Luksus',
        badgeKolor: 'red',
        gwiazdki: '★★★★★',
        dni: 7,
        wyzywienie: 'Śniadania',
        lotnisko: 'Warszawa',
        cena: 4299,
        lastminute: false,
        destination: 'dubaj',
        zdjecie: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&h=450&fit=crop',
        opis: 'Dubaj to miasto przyszłości – najwyższe wieżowce, luksusowe centra handlowe i sztuczne wyspy. Odkryj Burj Khalifa, Palm Jumeirah i tradycyjne suki w jednym niezapomnianym tygodniu.',
        wlaczone: ['Przelot w obie strony', 'Śniadania', 'Transfer z lotniska', 'Ubezpieczenie', 'Wycieczka do Burj Khalifa']
    },
    {
        id: 13,
        nazwa: 'Francja – Paryż',
        badge: 'Polecane',
        badgeKolor: '',
        gwiazdki: '★★★★☆',
        dni: 5,
        wyzywienie: 'Śniadania',
        lotnisko: 'Kraków',
        cena: 2599,
        lastminute: false,
        destination: 'francja',
        zdjecie: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&h=450&fit=crop',
        opis: 'Paryż – Miasto Miłości. Wieża Eiffla, Luwr, Wersal i niezliczone kawiarnie czekają na Ciebie. Romantyczy spacer nad Sekwaną o zmierzchu to przeżycie, którego nie zapomnisz.',
        wlaczone: ['Przelot w obie strony', 'Śniadania', 'Transfer z lotniska', 'Ubezpieczenie']
    },
    {
        id: 14,
        nazwa: 'Czechy – Praga',
        badge: 'Last Minute',
        badgeKolor: 'red',
        gwiazdki: '★★★★☆',
        dni: 4,
        wyzywienie: 'Śniadania',
        lotnisko: 'Warszawa',
        cena: 899,
        lastminute: true,
        destination: 'czechy',
        zdjecie: 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=800&h=450&fit=crop',
        opis: 'Praga to jedna z najpiękniejszych stolic Europy. Stare Miasto, Most Karola, zamek na Hradczanach i słynne czeskie piwo tworzą niezapomniany klimat tego bajkowego miasta.',
        wlaczone: ['Autokar lub lot', 'Śniadania', 'Ubezpieczenie', 'Zwiedzanie z przewodnikiem']
    },
    {
        id: 15,
        nazwa: 'Austria – Wiedeń',
        badge: 'Nowość',
        badgeKolor: 'green',
        gwiazdki: '★★★★★',
        dni: 5,
        wyzywienie: 'Śniadania',
        lotnisko: 'Kraków',
        cena: 1599,
        lastminute: false,
        destination: 'austria',
        zdjecie: 'https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800&h=450&fit=crop',
        opis: 'Wiedeń to europejska stolica muzyki i kultury. Pałac Schönbrunn, Opera Wiedeńska, Muzeum Historii Sztuki i wyśmienite cukiernie serwujące Sachertorte – to wszystko czeka na Ciebie.',
        wlaczone: ['Przelot w obie strony', 'Śniadania', 'Transfer z lotniska', 'Ubezpieczenie', 'Karta miejska']
    },
    {
        id: 16,
        nazwa: 'Japonia – Tokio',
        badge: 'Egzotyka',
        badgeKolor: 'red',
        gwiazdki: '★★★★★',
        dni: 12,
        wyzywienie: 'Śniadania',
        lotnisko: 'Warszawa',
        cena: 6499,
        lastminute: false,
        destination: 'japonia',
        zdjecie: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&h=450&fit=crop',
        opis: 'Tokio to miasto, gdzie tradycja spotyka nowoczesność. Świątynie i ogrody zestawione z neonowymi dzielnicami, sklepami anime i najlepszymi restauracjami na świecie.',
        wlaczone: ['Przelot w obie strony', 'Śniadania', 'Transfer z lotniska', 'Ubezpieczenie', 'Karta JR Pass (7 dni)']
    },
    {
        id: 17,
        nazwa: 'USA – Nowy Jork',
        badge: 'Bestseller',
        badgeKolor: 'green',
        gwiazdki: '★★★★★',
        dni: 10,
        wyzywienie: 'Bez wyżywienia',
        lotnisko: 'Warszawa',
        cena: 5999,
        lastminute: false,
        destination: 'usa',
        zdjecie: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&h=450&fit=crop',
        opis: 'Nowy Jork – miasto, które nigdy nie śpi. Empire State Building, Times Square, Central Park, Statua Wolności i Brooklyn Bridge to tylko wstęp do niezliczonych atrakcji Big Apple.',
        wlaczone: ['Przelot w obie strony', 'Transfer z lotniska', 'Ubezpieczenie', 'Karta do MoMA']
    },
    {
        id: 18,
        nazwa: 'Islandia – Reykjavik',
        badge: 'Nowość',
        badgeKolor: 'green',
        gwiazdki: '★★★★☆',
        dni: 7,
        wyzywienie: 'Śniadania',
        lotnisko: 'Gdańsk',
        cena: 3799,
        lastminute: false,
        destination: 'islandia',
        zdjecie: 'https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=800&h=450&fit=crop',
        opis: 'Islandia to kraj ognia i lodu. Gejzery, wodospady, zorza polarna i gorące źródła tworzą nieziemski krajobraz. Wycieczka do Błękitnej Laguny jest obowiązkiem.',
        wlaczone: ['Przelot w obie strony', 'Śniadania', 'Transfer z lotniska', 'Ubezpieczenie', 'Wejście do Błękitnej Laguny']
    },
    {
        id: 19,
        nazwa: 'Norwegia – Fiordy',
        badge: 'Polecane',
        badgeKolor: '',
        gwiazdki: '★★★★★',
        dni: 8,
        wyzywienie: 'Half Board',
        lotnisko: 'Warszawa',
        cena: 3499,
        lastminute: false,
        destination: 'norwegia',
        zdjecie: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&h=450&fit=crop',
        opis: 'Norweskie fiordy to jedne z najpiękniejszych krajobrazów na ziemi. Rejs po Sognefjord, wędrówki po górach i widok zorzy polarnej to przeżycia na całe życie.',
        wlaczone: ['Przelot w obie strony', 'Half Board', 'Transfer z lotniska', 'Ubezpieczenie', 'Rejs fiordami']
    },
    {
        id: 20,
        nazwa: 'Kenia – Safari',
        badge: 'Egzotyka',
        badgeKolor: 'red',
        gwiazdki: '★★★★★',
        dni: 10,
        wyzywienie: 'Full Board',
        lotnisko: 'Warszawa',
        cena: 7999,
        lastminute: false,
        destination: 'kenia',
        zdjecie: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&h=450&fit=crop',
        opis: 'Safari w Kenii to marzenie każdego miłośnika przyrody. Masai Mara, wielka migracja gnu, lwy, słonie i żyrafy w naturalnym środowisku. Nocleg w luksusowym obozie pod gwiazdami.',
        wlaczone: ['Przelot w obie strony', 'Full Board', 'Transfer z lotniska', 'Ubezpieczenie', 'Codzienne wyjazdy safari', 'Wizyta w wiosce Masajów']
    },
    {
        id: 21,
        nazwa: 'Cypr – Ayia Napa',
        badge: 'Last Minute',
        badgeKolor: 'red',
        gwiazdki: '★★★★☆',
        dni: 7,
        wyzywienie: 'All Inclusive',
        lotnisko: 'Katowice',
        cena: 1799,
        lastminute: true,
        destination: 'cypr',
        zdjecie: 'https://images.unsplash.com/photo-1504150558240-0b4fd8946624?w=800&h=450&fit=crop',
        opis: 'Ayia Napa to tętniący życiem kurort na Cyprze znany z krystalicznych plaż i bujnego życia nocnego. Plaża Nissi Beach to jedna z najpiękniejszych na Morzu Śródziemnym.',
        wlaczone: ['Przelot w obie strony', 'All Inclusive', 'Transfer z lotniska', 'Ubezpieczenie']
    },
    {
        id: 22,
        nazwa: 'Malta – Valletta',
        badge: 'Nowość',
        badgeKolor: 'green',
        gwiazdki: '★★★★☆',
        dni: 7,
        wyzywienie: 'Śniadania',
        lotnisko: 'Wrocław',
        cena: 1999,
        lastminute: false,
        destination: 'malta',
        zdjecie: 'https://images.unsplash.com/photo-1599576337096-e24f21f80d94?w=800&h=450&fit=crop',
        opis: 'Malta to mała wyspa z wielką historią. Stolica Valletta to najmniejsza stolica Unii Europejskiej wpisana na listę UNESCO. Jaskinie Błękitna Grota i Gozo zachwycą każdego.',
        wlaczone: ['Przelot w obie strony', 'Śniadania', 'Transfer z lotniska', 'Ubezpieczenie']
    },
    {
        id: 23,
        nazwa: 'Tunezja – Hammamet',
        badge: 'Promocja',
        badgeKolor: '',
        gwiazdki: '★★★★☆',
        dni: 8,
        wyzywienie: 'All Inclusive',
        lotnisko: 'Gdańsk',
        cena: 1499,
        lastminute: false,
        destination: 'tunezja',
        zdjecie: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=450&fit=crop',
        opis: 'Hammamet to jedno z najpopularniejszych tunezyjskich kurortów. Długie piaszczyte plaże, ciepłe Morze Śródziemne i przystępne ceny sprawiają, że jest to idealny cel dla rodzin.',
        wlaczone: ['Przelot w obie strony', 'All Inclusive', 'Transfer z lotniska', 'Ubezpieczenie']
    },
    {
        id: 24,
        nazwa: 'Czarnogóra – Budva',
        badge: 'Last Minute',
        badgeKolor: 'red',
        gwiazdki: '★★★★☆',
        dni: 7,
        wyzywienie: 'Half Board',
        lotnisko: 'Kraków',
        cena: 1699,
        lastminute: true,
        destination: 'czarnogora',
        zdjecie: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&h=450&fit=crop',
        opis: 'Budva to najpiękniejszy kurort Czarnogóry – Stare Miasto z weneckimi murami, plaże Jaz i Mogren, oraz bliskość Kotoru. Adriatyk w wydaniu bałkańskim.',
        wlaczone: ['Przelot w obie strony', 'Half Board', 'Transfer z lotniska', 'Ubezpieczenie']
    },
    {
        id: 25,
        nazwa: 'Kanary – Gran Canaria',
        badge: 'Bestseller',
        badgeKolor: 'green',
        gwiazdki: '★★★★☆',
        dni: 10,
        wyzywienie: 'All Inclusive',
        lotnisko: 'Warszawa',
        cena: 2399,
        lastminute: false,
        destination: 'hiszpania',
        zdjecie: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=450&fit=crop',
        opis: 'Gran Canaria to wyspa o tysiącu twarzy – złote wydmy Maspalomas, tętniące life Playa del Inglés i zielone wnętrze wyspy z sosnowymi lasami i kanionami.',
        wlaczone: ['Przelot w obie strony', 'All Inclusive', 'Transfer z lotniska', 'Ubezpieczenie']
    },
    {
        id: 26,
        nazwa: 'Bułgaria – Słoneczny Brzeg',
        badge: 'Promocja',
        badgeKolor: '',
        gwiazdki: '★★★☆☆',
        dni: 7,
        wyzywienie: 'All Inclusive',
        lotnisko: 'Katowice',
        cena: 1099,
        lastminute: false,
        destination: 'bulgaria',
        zdjecie: 'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800&h=450&fit=crop',
        opis: 'Słoneczny Brzeg to najpopularniejszy bułgarski kurort nad Morzem Czarnym. Długa piaszczysta plaża, mnóstwo atrakcji i przystępne ceny przyciągają turystów z całej Europy.',
        wlaczone: ['Przelot w obie strony', 'All Inclusive', 'Transfer z lotniska', 'Ubezpieczenie']
    },
    {
        id: 27,
        nazwa: 'Indie – Goa',
        badge: 'Egzotyka',
        badgeKolor: 'red',
        gwiazdki: '★★★★☆',
        dni: 12,
        wyzywienie: 'Śniadania',
        lotnisko: 'Warszawa',
        cena: 3299,
        lastminute: false,
        destination: 'indie',
        zdjecie: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&h=450&fit=crop',
        opis: 'Goa to indyjski raj dla backpackerów i miłośników relaksu. Kolonialna architektura portugalska, kolorowe targi, hinduskie świątynie i piękne plaże Arabskiego Morza.',
        wlaczone: ['Przelot w obie strony', 'Śniadania', 'Transfer z lotniska', 'Ubezpieczenie']
    }
];
